# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad1581cb4422eba9179bee886f60e66458bd1f1147f79405973dfe1436a8b7455833c1a2d0f7d470af22501c320580e8112a9474de6fb234e1006d3bd56e36dd

test:
  secret_key_base: 1e8b508e9f29d9ae1686589d8c292aca7cc58b87069780b79eb5b6e33f46c4a1cc980195511a301cb94ab9b7f5b28538d1ed8b192281d46accae364ceb688167

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
